# Setup
title:               Less Data, Same Happiness
tagline:             'An extended analysis'
description:         'An extension of the paper <a href="https://www.aeaweb.org/articles?id=10.1257/pol.1.1.75" target="_blank">Housing, Health, & Happiness (2009)</a>'
url:                 https://danieljsmarda.github.io
baseurl:             
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Daniel Smarda
  url:               
  email:             danieljsmarda@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
